apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freqtrade-bot.fullname" . }}-cfg
data:
  config.json: |
    {
      "dry_run": true,
      "dry_run_wallet": 1000,
      "max_open_trades": 1,
      "stake_currency": "USDT",
      "stake_amount": "unlimited",
      "timeframe": "5m",

      "exchange": {
        "name": "binance",
        "ccxt_config": { "enableRateLimit": true },
        "ccxt_async_config": { "enableRateLimit": true },
        "pair_whitelist": ["BTC/USDT", "ETH/USDT"],
        "pair_blacklist": []
      },

      "pairlists": [ { "method": "StaticPairList" } ],

      "entry_pricing": { "price_side": "ask", "use_order_book": false, "fallback": "last" },
      "exit_pricing":  { "price_side": "bid", "use_order_book": false, "fallback": "last" },

      "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "username": "admin",
        "password": "changeme-please",
        "jwt_secret_key": "replace-with-long-random"
      }
    }
